/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblo;

 import static Biblo.Libros.Libro; 
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Busr extends javax.swing.JFrame {

    DefaultTableModel tab1 = new DefaultTableModel();
    
    int Columna;
    
    public Busr() {
        initComponents();
        setLocationRelativeTo(null);
        tab1.addColumn("Titulo");
        tab1.addColumn("Autor");
        tab1.addColumn("Año.Publicacion");
        tab1.addColumn("Editorial");
        tab1.addColumn("Codigo");
        tab1.addColumn("Estado");
        
        this.Tabla3.setModel(tab1);
    }
    
    void Mostrar(){
        int filas=tab1.getRowCount();
        for(int i=0;i<filas;i++){
            tab1.removeRow(0);
        }
        
        for(int i = 0;i<Libro.size();i++){
            Object [] most = {Libro.get(i).titulo,Libro.get(i).autor,Libro.get(i).Año,Libro.get(i).editorial,Libro.get(i).codigo,Libro.get(i).estado};
            tab1.addRow(most);
        }
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txFiltrar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();
        BT_Cerrar = new javax.swing.JButton();
        BTV = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Filtrar ");

        txFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFiltrarActionPerformed(evt);
            }
        });
        txFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txFiltrarKeyTyped(evt);
            }
        });

        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Año.Publicacion", "Editorial", "Codigo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla3);

        BT_Cerrar.setText("X");
        BT_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CerrarActionPerformed(evt);
            }
        });

        BTV.setText("<<");
        BTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVActionPerformed(evt);
            }
        });

        jLabel3.setText("Titulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BTV)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BT_Cerrar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_Cerrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTV)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CerrarActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_BT_CerrarActionPerformed

    private void BTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVActionPerformed
        
        Libros Lv=new Libros();
        Lv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTVActionPerformed

    private void txFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFiltrarActionPerformed
       
        
        
    }//GEN-LAST:event_txFiltrarActionPerformed
private TableRowSorter trs;
    private void txFiltrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txFiltrarKeyTyped
     
        
              
        txFiltrar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txFiltrar.getText(), 0));
                if (txFiltrar == null){
                    txFiltrar.remove(0);
                    
                }
                Mostrar();
            }
            });
        trs =new TableRowSorter(tab1);
        Tabla3.setRowSorter(trs);
        
    }//GEN-LAST:event_txFiltrarKeyTyped

    private TableRowSorter trs2;
    private void txFiltrarKeyTyped2(java.awt.event.KeyEvent evt) {                                   
     
        
              
        txFiltrar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txFiltrar.getText(), 1));
                if (txFiltrar == null){
                    txFiltrar.remove(0);
                    
                }
                Mostrar();
            }
            });
        trs =new TableRowSorter(tab1);
        Tabla3.setRowSorter(trs);
    }
    private TableRowSorter trs3;
    private void txFiltrarKeyTyped3(java.awt.event.KeyEvent evt) {                                   
     
        
              
        txFiltrar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txFiltrar.getText(), 3));
                if (txFiltrar == null){
                    txFiltrar.remove(0);
                    
                }
                Mostrar();
            }
            });
        trs =new TableRowSorter(tab1);
        Tabla3.setRowSorter(trs);
    }private TableRowSorter trs4;
    private void txFiltrarKeyTyped4(java.awt.event.KeyEvent evt) {                                   
     
        
              
        txFiltrar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txFiltrar.getText(), 4));
                if (txFiltrar == null){
                    txFiltrar.remove(0);
                    
                }
                Mostrar();
            }
            });
        trs =new TableRowSorter(tab1);
        Tabla3.setRowSorter(trs);
    }
    private TableRowSorter trs1;
    private void txFiltrarKeyTyped1(java.awt.event.KeyEvent evt) {                                   
     
        
              
        txFiltrar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txFiltrar.getText(),5));
                if (txFiltrar == null){
                    txFiltrar.remove(0);
                    
                }
                Mostrar();
            }
            });
        trs =new TableRowSorter(tab1);
        Tabla3.setRowSorter(trs);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTV;
    private javax.swing.JButton BT_Cerrar;
    private javax.swing.JTable Tabla3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txFiltrar;
    // End of variables declaration//GEN-END:variables
}
