/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblo;

import java.util.ArrayList;

/**
 *
 * @author usuario
 */
public class Usuarios extends javax.swing.JFrame {

public static   ArrayList<RUser> User=new ArrayList<RUser>();
    
    public Usuarios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txuser = new javax.swing.JTextField();
        txDocumento = new javax.swing.JTextField();
        txpass = new javax.swing.JTextField();
        VER = new javax.swing.JPanel();
        BT_Registrar = new javax.swing.JButton();
        BT_Volver = new javax.swing.JButton();
        BT_Salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txEstado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mini.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconsneg.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Documento ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, -1));

        txuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txuserActionPerformed(evt);
            }
        });
        getContentPane().add(txuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 210, 30));
        getContentPane().add(txDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 150, 30));
        getContentPane().add(txpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 30));

        VER.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout VERLayout = new javax.swing.GroupLayout(VER);
        VER.setLayout(VERLayout);
        VERLayout.setHorizontalGroup(
            VERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        VERLayout.setVerticalGroup(
            VERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(VER, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 270, 50));

        BT_Registrar.setText("Registrar");
        BT_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 90, -1));

        BT_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flchneg.png"))); // NOI18N
        BT_Volver.setBorder(null);
        BT_Volver.setBorderPainted(false);
        BT_Volver.setContentAreaFilled(false);
        BT_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Volver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Next_page_64px_2.png"))); // NOI18N
        BT_Volver.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Next_page_64px_2.png"))); // NOI18N
        BT_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        BT_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xnombre.png"))); // NOI18N
        BT_Salir.setBorder(null);
        BT_Salir.setBorderPainted(false);
        BT_Salir.setContentAreaFilled(false);
        BT_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        BT_Salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        BT_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, 30));

        txEstado.setText("normal");
        getContentPane().add(txEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Next_page_64px_1_1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Next_page_64px_1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Next_page_64px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/77f975d35ee6debd8060f62a5fc2e43a.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 753, 367));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_BT_SalirActionPerformed

    private void BT_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VolverActionPerformed
       LOBY LV=new LOBY();
       LV.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BT_VolverActionPerformed

    private void BT_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_RegistrarActionPerformed
        
        User.add(new RUser(txuser.getText(),txDocumento.getText(),txpass.getText(),txEstado.getText()));
        System.out.println(User.get(0).Nombre);
        System.out.println(User.get(0).Correo);
        
        txuser.setText("");
        txDocumento.setText("");
        txpass.setText("");
        txEstado.setText("");
        
    }//GEN-LAST:event_BT_RegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Consulta C= new Consulta();
        C.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Registrar;
    private javax.swing.JButton BT_Salir;
    private javax.swing.JButton BT_Volver;
    private javax.swing.JPanel VER;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txDocumento;
    private javax.swing.JTextField txEstado;
    private javax.swing.JTextField txpass;
    private javax.swing.JTextField txuser;
    // End of variables declaration//GEN-END:variables
}
